### ISSUE TITLE
谢谢整理，提个建议老哥你这里面有部分回答不够全面啊只介绍了部分情况

### ISSUE THREAD

**Issue by ryanwlb** [yuanguangxin/LeetCode#1]
如果时间允许的话整理的更详细一点会更好也能帮助你复习提升，个人意见
如果有打赏链接麻烦贴一个，辛苦整理谢谢

**Comment by yuanguangxin** [comment]
嗯是，当时整理只是为了方便自己记忆，所以也没发知乎上。后续我会再仔细整理一下的包括算法题方面啥的。感谢关注。

发自我的iPhone
