### ISSUE TITLE
启动不了 全是J

### ISSUE THREAD

**Issue by huifeidezhipai** [yuanguangxin/LeetCode#4]

**Comment by huifeidezhipai** [comment]
Cannot start compilation: the output path is not specified for module "LeetCode".
Specify the output path in the Project Structure dialog.

**Comment by huifeidezhipai** [comment]
是java程序么，什么啊，完全启动不了

**Comment by yuanguangxin** [comment]
All my code is tested. Maybe sth wrong with your IDE, try to make directory 'src' as sources root.
